### ISSUE TITLE
Needs dark mode

### ISSUE THREAD

**Issue by connellrobert** [Perfect-Personnel-Placement/frontend#31]
**Is your feature request related to a problem? Please describe.**

In dark environments, the light mode is harmful to eyes due to an overabundance of blue light. To protect the health and well being of our users, we should implement a dark mode.

**Describe the solution you'd like**

Dark mode implemented to ensure our internal employees are not blinded by the light.

**Describe alternatives you've considered**

I have considered covering the screen with dark construction paper, but it makes it difficult to use the phone.

**Additional context**

![image](https://user-images.githubusercontent.com/47120126/129051639-1cef10eb-f27f-492c-a510-526d30134991.png)

**Comment by Kaichloe** [comment]
https://giphy.com/gifs/memecandy-LM89XJ5lVutN8u3SSZ
