### ISSUE TITLE
Too many Auburn colors

### ISSUE THREAD

**Issue by connellrobert** [Perfect-Personnel-Placement/frontend#34]
**Describe the bug**

The shear amount of Auburn colors in this application is absolutely astounding. This amount of matching orange and blues could cause irreparable harm to people's eyes that are unfamiliar with dealing with unfathomable disgusting  images. If this were to continue, we could potentially face extremely expensive hospital charges, lawsuits, and psychological harm. This should be taken out immediately!!!

**To Reproduce**
1. Go to any screen
2. Click on anything
3. Scroll down to anything
4. See terrible colors everywhere

**Expected behavior**

My eyes shouldn't bleed by looking at the screen.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: anything

**Additional context**

- [scientific proof](https://www.bennetteyecaremidwest.com/about/blog/352-is-my-eye-bleeding)

**Comment by redoral** [comment]
No.
