### ISSUE TITLE
react-native-picker-select destroys tests

### ISSUE THREAD

**Issue by calebmsword** [Perfect-Personnel-Placement/frontend#8]
**Describe the bug**
Any module which imports the `react-native-picker-select` package immediately causes a test suite to fail.

**To Reproduce**

1. Head to the directory for your local repo for this project and commit any code changes you have made.
2. `git checkout -b clients`
3. `git branch --set-upstream-to=origin/clients clients`
4. `git pull`
5. `npm test`

**Expected behavior**
I should be able to run tests on a component defined in a module that imports the `react-native-picker-select` package.

**Screenshots**
![image](https://user-images.githubusercontent.com/85499281/128422782-bb76b971-809c-4864-b645-e9810c2ec650.png)

**Additional context**
The solutions described [here](https://stackoverflow.com/questions/49263429/jest-gives-an-error-syntaxerror-unexpected-token-export), [here](https://github.com/facebook/jest/issues/2550) [here](https://stackoverflow.com/questions/66652403/jest-config-is-throwing-type-errorhandler-error-mixed-isfatal-boolean) and [here](https://github.com/callstack/react-native-testing-library/issues/703) have not fixed the problem.

**Comment by redoral** [comment]
Having this issue with our Batches screen as well.

**Comment by calebmsword** [comment]
Fixed the problem. It is an issue with Jest and React Native (it has nothing to do with Enzyme). Any third-party React Native library written in TypeScript but not compiled when uploaded to the npm registry breaks any test suite that imports that library (or any test suite which imports a module that imports the library).

The problem has something to do with Babel expecting to see JavaScript code while browsing node_modules files written in TypeScript. The Jest docs suggest a simple workaround that is easy to implement: see [description of transformIgnorePatterns](https://jestjs.io/docs/configuration#transformignorepatterns-arraystring) and [the section for the React Native](https://jestjs.io/docs/tutorial-react-native#transformignorepatterns-customization).

For our case, we need a little extra finagling to implement this workaround because we configure Jest using the `withEnzyme` method from `jest-expo-enzyme`. Here is an example of what needs to be done: 

```
const {withEnzyme} = require('jest-expo-enzyme');

const addSetup = (config) => {
  config.setupFilesAfterEnv.push('<rootDir>/__tests__/setup.js');
  config.testMatch = [
    '<rootDir>/src/component/Clients/ClientScreen.test.js',
  ];
  config.transformIgnorePatterns = [
    'node_modules/(?!(jest-)?(react-native|@react-native-community|expo(nent)?|@expo(nent)?/.*|react-navigation|@react-navigation/.*|@unimodules/.*|unimodules|sentry-expo|native-base|react-native-svg|@react-native-picker|react-native-picker-select)/)',
  ];
  return config;
}

module.exports = {
  projects: [
    addSetup(withEnzyme(require('jest-expo/android/jest-preset'))),
  ],
  collectCoverage: true,
  collectCoverageFrom: [
    '<rootDir>/src/**.{ts,tsx,js,jsx}',
    '<rootDir>/src/component/Header/Header.tsx',
    '<rootDir>/src/screens/Batches/Batches.tsx',
  ],
  coverageDirectory: 'coverage',
  coverageThreshold: {
    global: {
      statements: 70
    }
  },
}
```

Any third-party module which breaks tests needs to be added to the enormous string assigned to `config.transformIgnorePatterns`.
