### ISSUE TITLE
Coverage for Testing is not available

### ISSUE THREAD

**Issue by hpeninah** [Perfect-Personnel-Placement/frontend#9]
**Describe the bug**
There is no coverage displayed when code is being tested.

**To Reproduce**
1. npm run test

**Expected behavior**
Coverage should have been 

**Screenshots**
![Screenshot (35)](https://user-images.githubusercontent.com/72578792/128572942-784b4213-0be8-4830-a4a1-2f0e510b31a4.png)

**Comment by redoral** [comment]
Workaround is to manually define the file directories in the **collectCoverageFrom** argument in **jest.config.js** under **module.exports** Like so:
```
 collectCoverageFrom: [
    '<rootDir>/src/**.{ts,tsx,js,jsx}',
    '<rootDir>/src/components/batches/Header/index.tsx',
    '<rootDir>/src/components/batches/BatchStats/index.tsx',
    '<rootDir>/src/components/batches/BatchListItem/index.tsx',
    '<rootDir>/src/screens/Batches/index.tsx',
  ],
```
Can be considered as a fix and we can close this issue?

**Comment by hpeninah** [comment]
Yes, it can!
